### ISSUE TITLE
network interface not recognized on zyxel nas542

### ISSUE THREAD

**Issue by jkhunter** [OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown#104]
Hi, I'm using this script on my zyxel nas542. It could not recongized my network interfaces because the name schema looks different to all what I see before.

 "ip link" command returns this:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 16436 qdisc noqueue state UNKNOWN mode DEFAULT group default 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: ethip0: <BROADCAST,POINTOPOINT,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default 
    link/ether xxxxxxx peer ff:ff:ff:ff:ff:ff
3: egiga0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether xxxxxxx brd ff:ff:ff:ff:ff:ff
4: egiga1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether xxxxxxx brd ff:ff:ff:ff:ff:ff

```

I added "egiga"  to line 1169 of script and now it looks like it is working:
                `FORCE_NIC="$(ip link | awk -F': ' '/: en|: eth|: egiga|: wlan|: bond|: usb/ {print $2}')"`

**Comment by votdev** [comment]
Could you please try to use predictable device names on the system. this is exactly the use case why these type of naming schema was introduced. It seems this is disabled on your system.

References:
* https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/
* https://en.wikipedia.org/wiki/Consistent_Network_Device_Naming
* https://www.freedesktop.org/software/systemd/man/systemd.net-naming-scheme.html
* https://major.io/2015/08/21/understanding-systemds-predictable-network-device-names/

**Comment by jkhunter** [comment]
If you don't want to add egiga to the script, then it is fine for me. I fixed it for me and it is working so far. I will not change the name of the interfaces, because I do not have the knowledge how to do this. And because the interfaces are the only possible way to connect and run the server I could brick it by a misconfiguration.  And then I will have to handle with backups and unbricking it via serial console and a bootloader and so on...
