### ISSUE TITLE
Found 0 active socket(s) when connecting via Tailscale (Wireguard)

### ISSUE THREAD

**Issue by moerbb** [OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown#114]
There are never any active sockets found during the check, even though I'm connected to the machine via SSH.
I suspect this is because I connect to my machine via Tailscale (Wireguard). The problem has similarities with the [IPv6 issue #95](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown/issues/95) which has been fixed in the meantime.

**Comment by nrandon** [comment]
@moerbb This is not a lot to go on, so I am going to need a little more information from you to work out what not working. First I need to know which version of OMV you are running 5 or 6. (Currently I am only fixing OMV6, however if there a problem in 5 it in 6 as well i suspect). Secondly i need to know how you got Autoshutdown configured so can i have you config and a fake-mode or verbose log form you up to the point were the check start to cycle. I need the log so i can see how the script has configured itself toy you system (mist importantly if it detected you ip address's correctly). Final are you using only IP6 or a mix of 4 and 6 and can i have the address you connect to the OMV box on (i need only its internal address's). 

Form this I hope i can see how it set-up and if it should work. I need more debug latter I suspect.

Thanks

**Comment by moerbb** [comment]
Hi @nrandon, I’m using OMV6. My system is configured to get also an IPv6 address, but I’m only connecting via IPv4. The internal address is 192.168.1.11.
However, I now see in the logs that the error may have nothing to do with Tailscale at all, but with the last part of my machine’s IPv6 address. 
I’ve obfuscated my IPv6 a bit, but you can still see that the error seems to be related to it.
You can also see that I’m connected via Tailscale as well as locally, so active connections should be found on port 22.

`Jan 24 10:16:46 openmediavault autoshutdown[14895]: root: INFO: 'main(): XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
Jan 24 10:16:46 openmediavault autoshutdown[14895]: root: INFO: 'main(): Openmediavault-autoshutdown version: 6.0.6'
Jan 24 10:16:46 openmediavault autoshutdown[14895]: root: INFO: 'main(): Script md5sum: 92ab05bd8f21e14f374a69a1a91889e8'
Jan 24 10:16:46 openmediavault autoshutdown[14895]: root: INFO: 'FAKE-Mode: main(): /etc/autoshutdown.default loaded'
Jan 24 10:16:46 openmediavault autoshutdown[14895]: root: INFO: 'FAKE-Mode: main(): /etc/autoshutdown.conf loaded'
Jan 24 10:16:46 openmediavault autoshutdown[14895]: root: INFO: 'FAKE-Mode: main(): ---------------- Validate config ---------------------'
Jan 24 10:16:46 openmediavault autoshutdown[14895]: root: INFO: 'FAKE-Mode: main(): Checking config: /etc/autoshutdown.conf'
Jan 24 10:16:46 openmediavault autoshutdown[14895]: root: WARNING: 'FAKE-Mode: _validate_config(): CHECKCLOCKACTIVE set false not validating: UPHOURS and OVERRIDEUPHOURS'
Jan 24 10:16:46 openmediavault autoshutdown[14895]: root: INFO: 'FAKE-Mode: _validate_config(): rtc0 supports: wakealarm'
Jan 24 10:16:46 openmediavault autoshutdown[14895]: root: WARNING: 'FAKE-Mode: _validate_config(): WAKEALARM_SET set false not validating: WAKEALARM and OVERRIDEWAKEALARM'
Jan 24 10:16:46 openmediavault autoshutdown[14895]: root: WARNING: 'FAKE-Mode: _validate_config(): IPCHECK set false not validating: RANGE'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: WARNING: 'FAKE-Mode: _validate_config(): LOADAVERAGECHECK set false not validating: LOADAVERAGE'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: INFO: 'FAKE-Mode: _validate_config(): Kernel 5.15.0-0.bpo.2-amd64 supports power management modes:'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: INFO: 'FAKE-Mode: _validate_config(): Kernel supports: HYBRID-SLEEP (suspend to RAM and DISK)'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: INFO: 'FAKE-Mode: _validate_config(): Kernel supports: SUSPEND (suspend to RAM)'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: INFO: 'FAKE-Mode: _validate_config(): Kernel supports: HIBERNATE (suspend to DISK)'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: INFO: 'FAKE-Mode: _validate_config(): SHUTDOWNCOMMAND is set to: shutdown -h now'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: main(): ------------ Current config values ------------------'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: main(): ENABLE: true'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: main(): CYCLES: 6'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: main(): SLEEP: 180'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: main(): IPCHECK: false'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: main(): RANGE: 2..254,0x0..0xFFFF'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: main(): CHECKCLOCKACTIVE: false'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: main(): UPHOURS: 06:00..20:00'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: main(): WAKEALARM_SET: false'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: main(): WAKEALARM: 08:00'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: main(): WAKEALARM_UPHOURS: false'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: main(): CHECKSOCKETS: true'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: main(): NSOCKETNUMBERS: 21,22,80,3689,6991,9091,49152'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: main(): ULDLCHECK: true'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: main(): ULDLRATE: 50'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: main(): LOADAVERAGECHECK: false'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: main(): LOADAVERAGE: 40'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: main(): HDDIOCHECK: true'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: main(): HDDIO_RATE: 401'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: main(): SMARTCHECK: false'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: main(): CHECK_SAMBA: true'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: main(): CHECK_CLI: true'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: main(): CHECKPROCNAMES: true'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: main(): LOADPROCNAMES: smbd,nfsd,mt-daapd,forked-daapd'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: main(): TEMPPROCNAMES: in.tftpd'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: main(): PLUGINCHECK: false'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: main(): SYSLOG: true'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: main(): VERBOSE: true'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: main(): FAKE: true'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: main(): CHECK_SAMBA_CLIENTS: false'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: main(): LPREPEAT: 5'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: main(): TPREPEAT: 5'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: main(): NSOCKETPORTMAP: N/A'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: main(): NSOCKETIGNORESELF: false'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: main(): SHUTDOWNCOMMAND: shutdown -h now'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: main(): NET_IFACE_RETRY: 12'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: main(): NET_IFACE_SLEEP: 5'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: main(): FORCE_NIC: en eth wlan bond br usb'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: main(): RTC: rtc0'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: main(): OVERRIDEUPHOURS: N/A'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: main(): OVERRIDEWAKEALARM: N/A'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: main(): PINGLIST: N/A'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: main(): Available plugins found in: /etc/autoshutdown.d'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: main(): Plugin: /etc/autoshutdown.d/autounrarstatus'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: main(): Plugin: /etc/autoshutdown.d/clamav'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: INFO: 'FAKE-Mode: main(): ---------------- Network details ---------------------'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: INFO: 'FAKE-Mode: main(): Find active network interfaces and their IP addresses'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: _get_network_details(): Network interfaces: enp2s0'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: _get_network_details(): Network interfaces status: up'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: _get_network_details(): Network interfaces IPv4 address: 192.168.1.11'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: _get_network_details(): Network interfaces IPv4 address valid: true'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: _get_network_details(): Network interfaces IPv6 address: xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:16d'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: _get_network_details(): Network interfaces IPv6 address valid: true'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: INFO: 'FAKE-Mode: _get_network_details(): 'enp2s0' has IPv4 address: 192.168.1.11, IPv6 address: xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:16d'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: _get_network_details(): Network interfaces: br-7587c4c496a1'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: _get_network_details(): Network interfaces status: up'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: _get_network_details(): Network interfaces IPv4 address: 172.18.0.1'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: _get_network_details(): Network interfaces IPv4 address valid: true'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: _get_network_details(): Network interfaces IPv6 address: fe80::42:e2ff:fe8f:70d8'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: _get_network_details(): Network interfaces IPv6 address valid: true'
Jan 24 10:16:47 openmediavault autoshutdown[14895]: root: INFO: 'FAKE-Mode: _get_network_details(): 'br-7587c4c496a1' has IPv4 address: 172.18.0.1, IPv6 address: fe80::42:e2ff:fe8f:70d8'
[...]
Jan 24 10:16:48 openmediavault autoshutdown[14895]: root: INFO: 'FAKE-Mode: main(): ---------------- Script started ----------------------'
Jan 24 10:16:48 openmediavault autoshutdown[14895]: root: INFO: 'FAKE-Mode: main(): Registered trap on signal EXIT'
Jan 24 10:16:48 openmediavault autoshutdown[14895]: root: INFO: 'FAKE-Mode: main(): Waiting 1 second until the first check'
Jan 24 10:16:49 openmediavault autoshutdown[14895]: root: INFO: 'FAKE-Mode: main(): Checking network interface: enp2s0 - IPv4: 192.168.1.11, IPv6: xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:16d'
Jan 24 10:16:49 openmediavault autoshutdown[14895]: root: INFO: 'FAKE-Mode: main(): Checking network interface: br-7587c4c496a1 - IPv4: 172.18.0.1, IPv6: fe80::42:e2ff:fe8f:70d8'
Jan 24 10:16:49 openmediavault autoshutdown[14895]: root: INFO: 'FAKE-Mode: main(): 6 cycles until shutdown is issued'
Jan 24 10:16:49 openmediavault autoshutdown[14895]: root: INFO: 'FAKE-Mode: main(): ------------------------------------------------------'
Jan 24 10:16:49 openmediavault autoshutdown[14895]: root: INFO: 'FAKE-Mode: main(): New supervision cycle started, checking system activity'
Jan 24 10:16:49 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: __run_check(): Calling: _check_net_status()'
Jan 24 10:16:49 openmediavault autoshutdown[15560]: Error: "16d" does not look like a port.
Jan 24 10:16:49 openmediavault autoshutdown[15560]: Cannot parse dst/src address.
Jan 24 10:16:49 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: _check_net_status(): Port 21: Found no active connections'
Jan 24 10:16:49 openmediavault autoshutdown[15566]: Error: "16d" does not look like a port.
Jan 24 10:16:49 openmediavault autoshutdown[15566]: Cannot parse dst/src address.
Jan 24 10:16:49 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: _check_net_status(): Port 22: Found no active connections'
Jan 24 10:16:49 openmediavault autoshutdown[15572]: Error: "16d" does not look like a port.
Jan 24 10:16:49 openmediavault autoshutdown[15572]: Cannot parse dst/src address.
Jan 24 10:16:49 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: _check_net_status(): Port 80: Found no active connections'
Jan 24 10:16:49 openmediavault autoshutdown[15578]: Error: "16d" does not look like a port.
Jan 24 10:16:49 openmediavault autoshutdown[15578]: Cannot parse dst/src address.
Jan 24 10:16:49 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: _check_net_status(): Port 3689: Found no active connections'
Jan 24 10:16:49 openmediavault autoshutdown[15584]: Error: "16d" does not look like a port.
Jan 24 10:16:49 openmediavault autoshutdown[15584]: Cannot parse dst/src address.
Jan 24 10:16:49 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: _check_net_status(): Port 6991: Found no active connections'
Jan 24 10:16:49 openmediavault autoshutdown[15590]: Error: "16d" does not look like a port.
Jan 24 10:16:49 openmediavault autoshutdown[15590]: Cannot parse dst/src address.
Jan 24 10:16:49 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: _check_net_status(): Port 9091: Found no active connections'
Jan 24 10:16:49 openmediavault autoshutdown[15596]: Error: "16d" does not look like a port.
Jan 24 10:16:49 openmediavault autoshutdown[15596]: Cannot parse dst/src address.
Jan 24 10:16:49 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: _check_net_status(): Port 49152: Found no active connections'
Jan 24 10:16:49 openmediavault autoshutdown[14895]: root: INFO: 'FAKE-Mode: _check_net_status(): Found 0 active socket(s) from port(s): 21,22,80,3689,6991,9091,49152'
Jan 24 10:16:49 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: __run_check(): Calling: _check_docker_status()'
Jan 24 10:16:50 openmediavault autoshutdown[14895]: root: INFO: 'FAKE-Mode: _check_docker_status(): Found 0 active socket(s) from port(s): 21,22,80,3689,6991,9091,49152'
Jan 24 10:16:50 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: __run_check(): Calling: _check_users_status()'
Jan 24 10:16:50 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: _check_users_status(): Connected users:'
Jan 24 10:16:50 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: _check_users_status(): root     pts/0    100.110.20.49    18:34  -bash'
Jan 24 10:16:50 openmediavault autoshutdown[14895]: root: DEBUG: 'FAKE-Mode: _check_users_status(): root     pts/1    192.168.1.10      2:41  -bash'
Jan 24 10:16:50 openmediavault autoshutdown[14895]: root: INFO: 'FAKE-Mode: _check_users_status(): User: root on from pts/0 at 100.110.20.49'
Jan 24 10:16:50 openmediavault autoshutdown[14895]: root: INFO: 'FAKE-Mode: _check_users_status(): User: root on from pts/1 at 192.168.1.10'
Jan 24 10:16:50 openmediavault autoshutdown[14895]: root: INFO: 'FAKE-Mode: _check_users_status(): There are users connected -> no shutdown'
Jan 24 10:16:50 openmediavault autoshutdown[14895]: root: INFO: 'FAKE-Mode: main(): Active check failed, 6 cycles until shutdown ...'
Jan 24 10:16:50 openmediavault autoshutdown[14895]: root: INFO: 'FAKE-Mode: main(): Sleep for 180s'`

**Comment by nrandon** [comment]
yep look lie there a bug in the script i will try to fix it. Give me a bit of time to reproduce it and i get a fix ASAP

**Comment by nrandon** [comment]
Hi ok think I have a fix, Can you test it work for you? 

To test.
1. As root copy /usr/sbin/autoshutdown to /usr/sbin/autoshutdown.orig (best to keep the old one so you can restore it latter)
2. wget https://raw.githubusercontent.com/nrandon/openmediavault-autoshutdown/7a545f049fa1785062590b216168160519802cc1/usr/sbin/autoshutdown this should download the patched version. Make the file executable (chmod +x autoshutdown).
3. As root copy the downloaded autoshutdown over /usr/sbin/autoshutdown 
4. As root systemctl restart autoshutdown.service. restart with new script.

It should now hopefully except the IPv6 address correctly and find you port 22 active. If you need help to do the above let me know. Hopefully it should fix you issue and I can release the full fix latter today.

**Comment by moerbb** [comment]
When I connect locally with SSH, it works now:

Jan 24 13:02:35 openmediavault autoshutdown[6642]: root: DEBUG: 'FAKE-Mode: __run_check(): Calling: _check_net_status()'
Jan 24 13:02:35 openmediavault autoshutdown[6642]: root: DEBUG: 'FAKE-Mode: _check_net_status(): Port 21: Found no active connections'
Jan 24 13:02:35 openmediavault autoshutdown[6642]: root: DEBUG: 'FAKE-Mode: _check_net_status(): Port 22: Found active connections:'
Jan 24 13:02:35 openmediavault autoshutdown[6642]: root: DEBUG: 'FAKE-Mode: _check_net_status(): tcp 0 0 192.168.1.11:ssh 192.168.1.10:41600'
Jan 24 13:02:35 openmediavault autoshutdown[6642]: root: INFO: 'FAKE-Mode: _check_net_status(): Found 1 active connection(s) on port 22 (SSH) from: 192.168.1.10'
Jan 24 13:02:35 openmediavault autoshutdown[6642]: root: DEBUG: 'FAKE-Mode: _check_net_status(): Port 80: Found no active connections'
Jan 24 13:02:35 openmediavault autoshutdown[6642]: root: DEBUG: 'FAKE-Mode: _check_net_status(): Port 3689: Found no active connections'
Jan 24 13:02:35 openmediavault autoshutdown[6642]: root: DEBUG: 'FAKE-Mode: _check_net_status(): Port 6991: Found no active connections'
Jan 24 13:02:35 openmediavault autoshutdown[6642]: root: DEBUG: 'FAKE-Mode: _check_net_status(): Port 9091: Found no active connections'
Jan 24 13:02:35 openmediavault autoshutdown[6642]: root: DEBUG: 'FAKE-Mode: _check_net_status(): Port 49152: Found no active connections'
Jan 24 13:02:35 openmediavault autoshutdown[6642]: root: INFO: 'FAKE-Mode: _check_net_status(): Found 1 active socket(s) from port(s): 21,22,80,3689,6991,9091,49152'
Jan 24 13:02:35 openmediavault autoshutdown[6642]: root: INFO: 'FAKE-Mode: main(): Active check failed, 6 cycles until shutdown ...'
Jan 24 13:02:35 openmediavault autoshutdown[6642]: root: INFO: 'FAKE-Mode: main(): Sleep for 180s'

---

When I connect via Tailscale, it still doesn't work:

Jan 24 13:06:33 openmediavault autoshutdown[8512]: root: DEBUG: 'FAKE-Mode: __run_check(): Calling: _check_net_status()'
Jan 24 13:06:33 openmediavault autoshutdown[8512]: root: DEBUG: 'FAKE-Mode: _check_net_status(): Port 21: Found no active connections'
Jan 24 13:06:33 openmediavault autoshutdown[8512]: root: DEBUG: 'FAKE-Mode: _check_net_status(): Port 22: Found no active connections'
Jan 24 13:06:33 openmediavault autoshutdown[8512]: root: DEBUG: 'FAKE-Mode: _check_net_status(): Port 80: Found no active connections'
Jan 24 13:06:33 openmediavault autoshutdown[8512]: root: DEBUG: 'FAKE-Mode: _check_net_status(): Port 3689: Found no active connections'
Jan 24 13:06:33 openmediavault autoshutdown[8512]: root: DEBUG: 'FAKE-Mode: _check_net_status(): Port 6991: Found no active connections'
Jan 24 13:06:33 openmediavault autoshutdown[8512]: root: DEBUG: 'FAKE-Mode: _check_net_status(): Port 9091: Found no active connections'
Jan 24 13:06:33 openmediavault autoshutdown[8512]: root: DEBUG: 'FAKE-Mode: _check_net_status(): Port 49152: Found no active connections'
Jan 24 13:06:33 openmediavault autoshutdown[8512]: root: INFO: 'FAKE-Mode: _check_net_status(): Found 0 active socket(s) from port(s): 21,22,80,3689,6991,9091,49152'
Jan 24 13:06:33 openmediavault autoshutdown[8512]: root: DEBUG: 'FAKE-Mode: __run_check(): Calling: _check_docker_status()'
Jan 24 13:06:34 openmediavault autoshutdown[8512]: root: INFO: 'FAKE-Mode: _check_docker_status(): Found 0 active socket(s) from port(s): 21,22,80,3689,6991,9091,49152'
Jan 24 13:06:34 openmediavault autoshutdown[8512]: root: DEBUG: 'FAKE-Mode: __run_check(): Calling: _check_users_status()'
Jan 24 13:06:34 openmediavault autoshutdown[8512]: root: DEBUG: 'FAKE-Mode: _check_users_status(): Connected users:'
Jan 24 13:06:34 openmediavault autoshutdown[8512]: root: DEBUG: 'FAKE-Mode: _check_users_status(): root     pts/0    100.110.20.49     2:21  -bash'
Jan 24 13:06:34 openmediavault autoshutdown[8512]: root: INFO: 'FAKE-Mode: _check_users_status(): User: root on from pts/0 at 100.110.20.49'
Jan 24 13:06:34 openmediavault autoshutdown[8512]: root: INFO: 'FAKE-Mode: _check_users_status(): There are users connected -> no shutdown'
Jan 24 13:06:34 openmediavault autoshutdown[8512]: root: INFO: 'FAKE-Mode: main(): Active check failed, 6 cycles until shutdown ...'
Jan 24 13:06:34 openmediavault autoshutdown[8512]: root: INFO: 'FAKE-Mode: main(): Sleep for 180s'

---

The script only checks the network interfaces _enp2s0_ and _br-7587c4c496a1_, maybe that's the problem?

root@openmediavault:~# ip link show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: enp2s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether 38:ea:a7:a6:01:6d brd ff:ff:ff:ff:ff:ff
3: tailscale0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1280 qdisc pfifo_fast state UNKNOWN mode DEFAULT group default qlen 500
    link/none
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default
    link/ether 02:42:34:a7:c1:b2 brd ff:ff:ff:ff:ff:ff
5: br-7587c4c496a1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default
    link/ether 02:42:36:31:1c:25 brd ff:ff:ff:ff:ff:ff
[...]

**Comment by nrandon** [comment]
Form what you posed tailscale0 does not have an IP address so I do not think the port scan can use it, as it need interfaces with IP address so it can look up who is connected. However you can easily active this interface to see if the script can us it by setting the following advanced setting (see: https://raw.githubusercontent.com/OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown/master/etc/autoshutdown.default for more information) :

`FORCE_NIC="en eth wlan bond br usb tailscale"`


If this does not work can you post the output of the following ss command at the command prompt:-

`ss state established sport 22`

This should show how port 22 is connected (you may what to obfuscate so of the details) and is see if I can modify the script to do what needed. Note: You need to me connected on port 22 at the time of the test via the not working route ;). let me know either way as there is a bug in the script that needed to be fixed

**Comment by moerbb** [comment]
> Form what you posed tailscale0 does not have an IP address

`ip link show` doesn't show ip addresses. I could have posted the output of `ip a` instead.

> However you can easily active this interface to see if the script can us it by setting the following advanced setting 

I did not know about this advanced setting. Now it works! :)

**Comment by nrandon** [comment]
That grate news glad we got it fixed. Give me a bit and I release the patched script as it fixes the IPv6 issues found.

**Comment by nrandon** [comment]
Fix is released as 6.0.7 closing issues
