### ISSUE TITLE
Exlude ips

### ISSUE THREAD

**Issue by e-ru** [OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown#116]
Instead of specifying the ips that need to be checked, specifying also ips that are excluded from the check would be great.

Great Plugin!!
Regards
Erik

**Comment by nrandon** [comment]
@e-ru I been thinking about this and I cannot think of a good use case for it, that is I can always do the same using the current interface. Can I have an example of what you are looking for to check I am not missing something ?

**Comment by nrandon** [comment]
closing issues as no response so I cannot get a use-case for the change re-open if a use case is presented

**Comment by e-ru** [comment]
Hi

Sorry for the delay. i had a thinking mistake in my idea, so i also don't have a good use case for it. closing this is fine.

thx

**Comment by nrandon** [comment]
NP if you do come-up with a use-case let me know
