### ISSUE TITLE
Different Subnets

### ISSUE THREAD

**Issue by venrael** [OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown#12]
Can you please add the possibility to use different subnets. 

Right now my openmediavault ist connected to let's say: 192.168.0.22 and my Media Player is in a different subnet: 192.168.1.23 

The ping_range only returns clients from 192.168.0.0.
Even if i specify in the ip-range supervision configuration the media player ip directly: 192.168.1.23  it won't be recognized / pinged by the autoshutdown.

Please please make this enchancement happen

**Comment by walterheisenberg** [comment]
for such a special case try the pinglist-option
see https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown/blob/master/etc/autoshutdown.default
under "PINGLIST". You can add PINGLIST="/path/to/your/pinglist" to /etc/autoshutdown.conf
