### ISSUE TITLE
Error: an inet prefix is expected rather than "90:80" for _check_container_status()

### ISSUE THREAD

**Issue by tiktak24** [OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown#120]
All my containers are running on a stack which had no network specified

Im running on OMV version 6.0.27-1 with Autoshutdown version 6.0.8

I believe this happened when the stack was created it created a new network automatically as i didnt specify one in the docker compose and assigned all the containers to be a part of the stack. had a look at the source code a little bit and found it wasnt finding the ip address of the container in the newly created bridge network as it was looking in `.NetworkSettings.IPAddress` of the `docker container inspect` result but in the generated one this value was blank and the ip address was not blank in `.NetworkSettings.Networks.{name of generated network}.IPAddress`.

The solution was to change the containers to use the default bridge network or add network_mode: bridge to the service in the docker compose file.

I assume creating a network manually will not have this value empty and is an issue just with the automatically generated network but im not too sure.

Heres logs of before and after what it looks like, with the after having ports 8096 and 9000 in use and 8989 not in use all on the default bridge network and the rest still using the other network.
Also logs of the result from `docker container inspect` on two containers one with the default network and another with the one that was created when i made the stack.

[autoshutdown after.log](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown/files/8703950/autoshutdown.after.log)
[autoshutdown before.log](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown/files/8703951/autoshutdown.before.log)
[Default Network.txt](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown/files/8704006/Default.Network.txt)
[Generated Network.txt](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown/files/8704007/Generated.Network.txt)

**Comment by nrandon** [comment]
@tiktak24 fix for this should be on it way sorry it taken me ages to get to this can you verify this on the 6.0.9 release. thanks

**Comment by tiktak24** [comment]
@nrandon had a look on 6.0.9, looks like its fixed now. thanks for that
