### ISSUE TITLE
_check_smart() function doesn't work properly

### ISSUE THREAD

**Issue by pawelseweryn** [OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown#122]
I've found a issue with _check_smart function not working properly - there is a mistake in smartctl command - it checks for `$(hdd)` (sda, sdb, etc.) instead of `/dev/$(hdd)` (/dev/sda, /dev/sdb, etc.). As a result it doesn't detect SMART test is running because of "device not found" error. 

System: Linux homenas 5.16.0-0.bpo.4-amd64 #1 SMP PREEMPT Debian 5.16.12-1~bpo11+1 (2022-03-08) x86_64 GNU/Linux
Plugin version: openmediavault-autoshutdown 6.0.9

Actual code:
`smartctl --all --nocheck=standby "${hdd}" || true)"`
Corrected code: 
`smartctl --all --nocheck=standby "/dev/${hdd}" || true)"`
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown/blob/44867d109ab29ce45128785af1666bb34aaad466/usr/sbin/autoshutdown#L1002

Please find attached log before and after correction. 
[autoshutdown-after.log](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown/files/10328744/autoshutdown-after.log)
[autoshutdown-before.log](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown/files/10328745/autoshutdown-before.log)

**Comment by ryecoaaron** [comment]
fixed in next release - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown/commit/3fb2870315102dd5c3d2aee0941180ff72014ec9
