### ISSUE TITLE
Installed omv-extras but no openmediavault-autoshutdown

### ISSUE THREAD

**Issue by Glydric** [OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown#123]
after run `sudo apt install openmediavault-autoshutdown` this is the result 
`E: Unable to locate package openmediavault-autoshutdown`
on intel cpu

**Comment by ryecoaaron** [comment]
This really should be a post on the forum.

Click the apt clean button in omv-extras.  Did that help?  Did you just do an upgrade?
