### ISSUE TITLE
wake on lan issue in omv6 caused problems 

### ISSUE THREAD

**Issue by hblek** [OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown#127]
Wake on lan issue makes the use of autoshutdown feature problematic.

It seems that due to security the wake-on setting of the nic was disabled. 
I found a solution to solve this issue in:
https://dev.to/zakery1369/enable-wake-on-lan-on-debian-4ljd
I used the description to make a reboot persistent solution for my OMV6 installation, which is tested and working.

Maybe an option to add this repair in a future update of the plugin.
Kind regards, Henk

**Comment by ryecoaaron** [comment]
Enabling wake on lan for a network interface is already in the OMV web interface in the Network -> Interfaces section.

![image](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown/assets/1914475/2d2cc0ce-a8db-47cf-a526-40627e10685e)
