### ISSUE TITLE
/proc/self/loginuid: File or Path not found.

### ISSUE THREAD

**Issue by kefor** [OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown#130]
Hi, 

I got the following error when using the Autoshutdown addon:

autoshutdown[27005]: /usr/sbin/autoshutdown: Line 95: /proc/self/loginuid: File or Path not found.

**Comment by ryecoaaron** [comment]
What kind of system?  What version of OMV?  That file really should exist.
