### ISSUE TITLE
error in /usr/sbin/autoshutdown

### ISSUE THREAD

**Issue by Bulmer** [OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown#131]
I am using a fork of your code, for a non-openmediavault Debian server.
I am getting the following error which results in the occasional total shutdown.
```/usr/sbin/autoshutdown: line 924: 0.00: syntax error: invalid arithmetic operator (error token is ".00")```

**Comment by ryecoaaron** [comment]
It looks like the fork has changed something because line 924 is blank in the code in this repo.  I would ask the person who forked the script for help.
