### ISSUE TITLE
How can I set a custom SHUTDOWNCOMMAND ?

### ISSUE THREAD

**Issue by Number-313** [OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown#133]
I would like to run a script instead of using the default shutdown command...

I've tried editing the autoshutdown.default file, and it didn't work.

I've tried editing autoshutdown.conf file, but it gets overwritten.

I've tried entering the path of my script in the "expert settings", but it just runs the script before even starting the checks...

Am I missing something ? I need help please.

**Comment by ryecoaaron** [comment]
It isn't possible.  The code only allows one of the options from the plugin's Shutdown command dropdown.

**Comment by Number-313** [comment]
Alright,  I found a workaround : I simply changed the shutdown command.

Locate your shutdown command :

`which shutdown`

For me it returned :

`/usr/sbin/shutdown`

Now backup the file :

`mv /usr/sbin/shutdown /usr/sbin/shutdown.orig`

Now create a new shutdown file with the path of your script :

`vi /usr/sbin/shutdown`

`/myscriptpath/shutdownscript.sh`

If you used the `shutdown` command in your script, change it now to `shutdown.orig`
Now, whenever I use `shutdown`, it plays my script that ends with shutdown.orig
