### ISSUE TITLE
fresh insrtall no shutdown, no logging (except start/stop within syslog)

### ISSUE THREAD

**Issue by dkotte** [OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown#135]
openmediavault-autoshutdown is set to monitor HDD activity only (9999kb)
no logging regarding ressource activity or shutting-down
Most current versions of raspbian, openmediavault, openmediavault-autoshutdown 
ideas?
Is there a documentation somewhere?
THX
Dirk

**Comment by ryecoaaron** [comment]
You would better off asking your question on the forum.  I don't actually use the plugin and almost no one else will see this issue.
Here are the docs (other than reading the script):
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown/blob/master/README.md
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown/blob/master/etc/autoshutdown.default
https://forum.openmediavault.org/index.php?thread/5488-if-autoshutdown-doesn-t-work/&postID=49271&highlight=autoshutdown#post49271

**Comment by dkotte** [comment]
Hi,
Thanks for pointing this out, but the problems disappeared after I wrote the problem report. (I have been testing this for 2 days.)
Now the system is shutting down when idle and I see syslog entries regarding activity and scheduled shutdown.
