### ISSUE TITLE
Setting OVERRIDEWAKEALARM is not possible for non-English environments

### ISSUE THREAD

**Issue by myrck** [OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown#136]
If I use the day of the week in English, the validation fails. If I don't specify the day of the week in English, setting the alarm in the `_set_wakealarm()` function doesn't work because it expects it in English.

https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown/blob/8f873743a32c449a24a02e2da13e9ba8f0bf2ae6/usr/sbin/autoshutdown#L1090

should be:

```bash
local -r short_days="$(LC_ALL=C locale abday | sed 's:;:|:g')" 
```

**Comment by myrck** [comment]
With `export LC_ALL=C.UTF-8` at the top of the script it also works.

**Comment by ryecoaaron** [comment]
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown/commit/431e84a52b669ff78f40582de66b3320de13e6d3
