### ISSUE TITLE
Make autoshutdown more intuitive for user

### ISSUE THREAD

**Issue by Frogdaddy** [OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown#18]
Currently there are some options/priorities which are optional, but not all.  This requires the user to have to fake or fool the higher priority conditions in order to fall to the desired lower priority conditions (false IP to cause ping failure).  For example, one of the higher priorities relies on the ability/inability to ping devices on a network.  With a home network these devices may remain online forever.  Therefore, the condition for this priority remains in effect and system will never shutdown and lower configured priorities will never get observed as well as never satisfy shutdown criteria.  

At times it may not be desirable to have to meet so many checks to allow for a single condition to be met and invoke the shutdown.  In my environment, I'd like to just shutdown based on idleness, hddio, or cpu thresholds.  Those are pretty straightforward but again may never get met because of higher priorities (negative or positive depending how a user views the condition) being satisfied on a continuous basis.  Currently, lower priorities do have enable/disable switches.  The higher priorities do not and must have entries.

One additional observation, when we changed the IP (bogus or non-pingable) or service port to 9999 it appears according to log that old values were being checked.  It could've also been that an amount of time of the cycle needed to take place to observe newly entered values.

**Comment by davidh2k** [comment]
The IP Range must not have an entry, you can already see that in the readme at https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown/blob/master/etc/autoshutdown.default#L31

I admit that it is not in the Plugin, maybe Ryecoaaron is so kind to change the entry in the plugin and add the note that it can be simply filled with a '-' sign so the check is ignored.

Greetings
David

**Comment by walterheisenberg** [comment]
you can add RANGE="-" to Expert Settings. It should overwrite the IP-Range set above via GUI

**Comment by ryecoaaron** [comment]
Add note about entering '-' in 3.0.4.

**Comment by Wikibear** [comment]
- as default was a nice setting to start with ASD.

**Comment by nrandon** [comment]
I improved documentation ad GUI hopefully this addresses this.
