### ISSUE TITLE
Make hidden and implicit behaviour configurable

### ISSUE THREAD

**Issue by Flachzange** [OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown#21]
It seems that the autoshutdown plugin has a few hidden settings. For example

- Extra Check for connected users on the CLI if other processes are negative

- Extra Samba-Check for connected Clients only if other processes are negative

There might be more but these are the one that affect me personally and I need to remove the checks in the script manually for my use cases. 

**My suggestion: add two checkboxes to the web ui to make these extra checks optional.**

As far as I see, there are [others](http://forums.openmediavault.org/index.php/Thread/8378-Autoshutdown-Disable-SMBSTATUS-Check/) that wish the same.

Why?

**Extra Samba check:** My windows clients should connect to the NAS if available via network drive. If not, no problem. However, when the NAS is already switched on when my clients connect to the NAS, the above mentioned samba checks prevents the NAS from sleeping although I don't actually need the NAS. From an end user perspective I would simply add the samba port to the list of ports when I want to prevent shudown. The implicit extra check is hard to understand.

**Extra CLI check:** For an interactive system this check makes sense. This is why I wouldn't remove it completely. However, a NAS isn't usually interactive and the CLI check seems to apply for SSH sessions as well. It happens all the time that forget to logout from an SSH session. This session then prevents the autoshutdown script to suspend the NAS although there is no load on the system.

**Comment by davidh2k** [comment]
About the samba check - This is not the fault of the plugin but windows - the connections kept alive permanently, thus the socket is allways there. At least, thats what I experienced and thus stood away from using the network drive feature. At least thats my experience about it. So you actually have to remove the samba port from beeing checked.

And about the cli check: How can you forget to logout from ssh? ^^

Greetings
David

**Comment by Flachzange** [comment]
Hey David.

It's not about a fault of the plugin. It works correct if that behaviour is what you want, My point is that there are two hard-coded checks that cannot be configured but prevent a proper autoshutdown in some instances.

Regardless of any samba ports configured (my list of ports is empty), the above quoted extra check prevents the shutdown of the NAS when my windows client established a network drive connection to the NAS or if I am logged in using SSH. My expectation is actually that I can control the behaviour, either by specifying samba ports (example 1) or SSH ports (example 2).

Cheers!
Christoph

**Comment by walterheisenberg** [comment]
Samba:
remove the Samba check, as David said.

SSH:
It makes absolutely no sense to shutdown the server if anyone is connected via SSH. Maybe a user wants to do something on the CLI remotely and the Server is shutting down ...
Just set your SSH client a timeout, so that it disconnects automatically or don't forget to log out.

**Comment by ryecoaaron** [comment]
This was easy enough to fix.  So, it is added to 3.0.4.

**Comment by Flachzange** [comment]
Much appreciated guys :thumbsup:
