### ISSUE TITLE
HDDIO only look for sda

### ISSUE THREAD

**Issue by christoph5180** [OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown#24]
i have set the hddio to 400 and a sleep time 120. when i start a big file transfer (150MB/s over 30min) the log show:
'HDD-IO: '/dev/sda -> (last 120s): r: 36.4 w: 12.1 is under 400 -> next HDD'
'HDD-IO all checks for HDD-IO finished'
file transfer is between sdc (luks /dev/mapper/luks-1) and sdd (luks /dev/mapper/luks-2)

**Comment by ryecoaaron** [comment]
It actually loops through all the mounted drives mounted starting with /dev/sd.  What is the output of: mount

**Comment by christoph5180** [comment]
the output is:
/dev/mapper/luks-1 on /export/data type btrfs (rw,relatime,space_cache,autodefrag,subvolid=5,subvol=/data)
/dev/mapper/luks-2 on /media/backup type btrfs (rw,relatime,space_cache,subvolid=5,subvol=/)

it's possible to extend the loops over the /dev/mapper/*?

**Comment by ryecoaaron** [comment]
No offense but when you only post the output of mount that you think is important, it doesn't help completely since I don't use this plugin and don't have luks setup to simulate.  I also need the output of  iostat -kd

**Comment by christoph5180** [comment]
iostat -kd
Linux 4.6.0-0.bpo.1-amd64 (openmediavault)      02.12.2016      _x86_64_        (2 CPU)

Device:            tps    kB_read/s    kB_wrtn/s    kB_read    kB_wrtn
sda               0,73         4,04         9,88    3140589    7676152
sdd              18,41      3151,97       148,64 2449341055  115506320
sde              18,37      3152,08       148,50 2449426743  115399160
sdc              18,39      3151,76       148,67 2449177335  115526076
sdb              18,41      3151,82       148,81 2449222275  115634696
dm-0             51,86      3151,68       148,81 2449109096  115634696
dm-1             51,84      3151,62       148,67 2449064176  115526076
dm-2             51,86      3151,83       148,64 2449227820  115506320
dm-3             51,86      3151,94       148,50 2449313480  115399160
sdf              95,79         0,96      6131,21     748806 4764450460
dm-4             96,11         0,82      6131,19     634880 4764439080
sdg              95,85         1,09      6131,06     846676 4764331044
dm-5             96,08         0,95      6131,06     740200 4764331044

sdb to sdg are luks encrypted.
example:
cryptosetup luksOpen /dev/sdf luks-1 |luks-1 is a name given by me
to access the encrypted devices, luks mapped the devices to /dev/dm-4
and create a link from /dev/mapper/luks-1 to /dev/dm-4
my mount instruction: mount /dev/mapper/luks-1 /media/backup

**Comment by ryecoaaron** [comment]
There is a problem.  The drive name in the output of mount doesn't match the drive name in iostat.  I didn't write this script.  So, I will have to look more into it to see how it works and how to change it.  That may take a few days.

**Comment by disperun** [comment]
@ryecoaaron I think the main problem is about the line 803 in the autoshutdown.sh.

`for OMV_HDD in $(mount -l | grep /dev/sd | sed 's/.*\(sd.\).*/\1/g' | sort -u); do`
`OMV_IOSTAT="$(egrep ^${OMV_HDD} $HDDIOTMPDIR/iostat.txt)"`

The OMV_HDD var which is filled there only checks for "sdX" devices against the mounted drives list and then compare them to the iostat output. 
I think this statement has to be extended for checking also for "mdX", "dm-X" and further standard device names which might be possibly used.

**Comment by ryecoaaron** [comment]
I agree but that entire logic needs to be rewritten and I don't have a way to test.  Feel free to submit a pull request.

**Comment by nrandon** [comment]
fixed
