### ISSUE TITLE
if wake on lan the system won't power off at the first time

### ISSUE THREAD

**Issue by it4workflow** [OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown#29]
powered on by | shutdown by terminal, ssh, webinterface | shutdown by autoshutdown
------------ | ------------- | -------------
power button | yes, ok | yes, ok
wake on lan (wol) | yes, ok | yes, not really**

** The system powers off, the power led is off ... for 3 seconds, then the system magically powers on again. The second time the system powers off, it stays off?!

So what is the difference of `shutdown -h now` by autoshutdown the first time after wake on lan with the others called `shutdown -h now`?

omv 2.2.13 (stone burner)
Linux 3.16.0-0.bpo.4-amd64
Intel(R) Core(TM) i3-6100T CPU @ 3.20GHz
ASUS B150M-C (latest BIOS 3016 12/27/2016)

**Comment by ryecoaaron** [comment]
There is no difference between those shutdown calls.  Your motherboard is very new and needs a newer kernel than the 3.16 kernel.  The 4.9 kernel that OMV 3.x may work better.

**Comment by it4workflow** [comment]
There's no subcall or anything else (user issue, pre-suspend, etc.)?

It's hard to believe that the very same command of shutdown results in different behaviours (at a certain constellation), so i think more about an motherboard issue. But ok, i will try OMV 3.x in the next days...

**Comment by it4workflow** [comment]
just fyi: if i add `acpi=noirq` in `grub.conf` non of the constellations mentioned above won't work as it should, respectively its not reproducable and the behaviours are rather by chance.

**Comment by nrandon** [comment]
cannot reproduce obsolete
