### ISSUE TITLE
shutdown if HDD's sleep

### ISSUE THREAD

**Issue by Mister-XY** [OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown#31]
Hello, i miss the functions for the plugin, that's the plugin check's if the HDD's standby or in spindown mode. 
I my case i need only check for pingable IP's and are there no pingable IP, then check if the HDD sleep. If there are both (ore more) HDD in Spindown/standby mode, then shutdown.

**Comment by Wikibear** [comment]
+1 That would be a nice feature. If you have HDDs sleep for 10 minutes i don't need a running system. Using M2 as well...

**Comment by nrandon** [comment]
I think this can now be done using hddIo check
