### ISSUE TITLE
Cannot get UL- or DL-Rate, prevent shutdown

### ISSUE THREAD

**Issue by yo1frenchtoast** [OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown#34]
`Aug 30 09:55:55 openmediavault logger: autoshutdown[23056]: INFO: ' new supervision cycle started - check active hosts or processes'
Aug 30 09:55:55 openmediavault logger: autoshutdown[23056]: INFO: ' Checking the time: stay up or shutdown ...'
Aug 30 09:55:55 openmediavault logger: autoshutdown[23056]: INFO: ' System is in Shutdown-Range. Do further checks ...'
Aug 30 09:55:55 openmediavault logger: autoshutdown[23056]: INFO: ' retrieve list of active IPs for 'eth2' ...'
Aug 30 09:55:56 openmediavault logger: autoshutdown[23056]: INFO: ' No active IPs in the specified IP-Range found'
Aug 30 09:55:56 openmediavault logger: autoshutdown[23056]: INFO: ' Check Connections for 'eth2''
Aug 30 09:55:57 openmediavault logger: autoshutdown[23056]: INFO: ' ULDL-Traffic-Check for 'eth2''
Aug 30 09:55:57 openmediavault logger: autoshutdown[23056]: INFO: ' eth2: over the last 180 seconds: DL:  kB/s; UL:  kB/s'
Aug 30 09:55:57 openmediavault logger: autoshutdown[23056]: INFO: ' eth2: UL- or DL-Rate is over 50 kB/s -> no shutdown'
Aug 30 09:55:57 openmediavault logger: autoshutdown[23056]: INFO: ' sleep for 180s.'
`

**Comment by Huberer01** [comment]
Issue is still on. With OMV v4 and Debian 9 back ports kernel 4.12. Here is my part of the log file:

`Oct  6 01:57:27 HomeServer root: autoshutdown[891]: INFO: ' new supervision cycle started - check active hosts or processes'
Oct  6 01:57:27 HomeServer root: autoshutdown[891]: INFO: ' retrieve list of active IPs for 'enp0s25' ...'
Oct  6 01:57:28 HomeServer root: autoshutdown[891]: INFO: ' No active IPs in the specified IP-Range found'
Oct  6 01:57:28 HomeServer root: autoshutdown[891]: INFO: ' Check Connections for 'enp0s25''
Oct  6 01:57:28 HomeServer root: autoshutdown[891]: INFO: ' ULDL-Traffic-Check for 'enp0s25''
Oct  6 01:57:28 HomeServer root: autoshutdown[891]: INFO: ' enp0s25: over the last 300 seconds: DL: inf kB/s; UL: inf kB/s'
Oct  6 01:57:28 HomeServer root: autoshutdown[891]: INFO: ' enp0s25: UL- or DL-Rate is over 50 kB/s -> no shutdown'
Oct  6 01:57:28 HomeServer root: autoshutdown[891]: INFO: ' sleep for 300s.'`

Without recognizing the ULDL-rate the server is still on

**Comment by yo1frenchtoast** [comment]
Can you provide ouput of command 'ifconfig enp0s25' ?

**Comment by Huberer01** [comment]
Here is the output:

`root@HomeServer:/# ifconfig enp0s25
enp0s25: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.200  netmask 255.255.255.0  broadcast 192.168.1.255
        ether 90:1b:0e:48:94:22  txqueuelen 1000  (Ethernet)
        RX packets 4747  bytes 1950174 (1.8 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 10157  bytes 7629064 (7.2 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 20  memory 0xf7d00000-f7d20000  

root@HomeServer:/#

**Comment by Huberer01** [comment]
It looks like that Debian doesn't recognize the broadcast correct, which should be 192.168.1.1

**Comment by yo1frenchtoast** [comment]
Thank you, I had exactly the same problem on my OMV3 on Debian 8 jessie

This commit should actually fix the issue, as the ifconfig ouput has changed between Debian wheezy and jessie, it cannot correctly grep bytes counters

You can try it by cloning from my repo (https://github.com/yo1frenchtoast/openmediavault-autoshutdown), copy file openmediavault-autoshutdown/usr/sbin/autoshutdown.sh to /usr/sbin/autoshutdown.sh and relaunch autoshutdown service

Please feel free to ask for help if you experience any problem

**Comment by Huberer01** [comment]
Hello,

 

thanks for your feedback. I found your pull requests on the "official"-ASD-Github-side and copied them into autoshutdown.sh. As well your fix for the port check (which I don't need at the moment).

It looks that everything is working perfect under OMV v4 with Debian 9.

 

I have to say thank you, thank you for your help.

 

Huberer

 

Gesendet: Freitag, 06. Oktober 2017 um 17:04 Uhr
Von: "Yoan Tanguy" <notifications@github.com>
An: OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown <openmediavault-autoshutdown@noreply.github.com>
Cc: Huberer01 <huberer@gmx.at>, Comment <comment@noreply.github.com>
Betreff: Re: [OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown] Cannot get UL- or DL-Rate, prevent shutdown (#34)


Thank you, I had exactly the same problem on my OMV3 on Debian 8 jessie

This commit should actually fix the issue, as the ifconfig ouput has changed between Debian wheezy and jessie, it cannot correctly grep bytes counters

You can try it by cloning from my repo (https://github.com/yo1frenchtoast/openmediavault-autoshutdown), copy file openmediavault-autoshutdown/usr/sbin/autoshutdown.sh to /usr/sbin/autoshutdown.sh and relaunch autoshutdown service

Please feel free to ask for help if you experience any problem

**Comment by yo1frenchtoast** [comment]
You're welcome =)
