### ISSUE TITLE
Change shebang from #!/bin/bash to #!/bin/sh

### ISSUE THREAD

**Issue by x86dev** [OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown#35]
While investigating why other hooks in /etc/pm were not called after the "autoshutdown resume/thaw" hook was called, I changed the shebang from #!/bin/bash to #!/bin/sh, and this apparently made all the other hooks get called again.

Also, IMHO there's no need of using bash as the (sub-)shell in that regard -- sh should be enough to get the job done.

**Comment by ryecoaaron** [comment]
I don't think I have ever seen a script work with sh that didn't work with bash.  Which script did you change it in?
