### ISSUE TITLE
_check_networkconfig within ASD under OMV v4 with 4.12 back port kernel not working

### ISSUE THREAD

**Issue by Huberer01** [OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown#37]
Hello,

unfortunately ASD can't handle correct the broadcast-address of the ethernet card. Therefore the server goes down, even IP-scanning is enabled. Here is the output of the log:

`Oct  5 14:47:22 HomeServer root: autoshutdown[903]: INFO: ' Reading NICs ,IPs, ...'
Oct  5 14:47:22 HomeServer root: autoshutdown[903]: INFO: ' NIC 'enp0s25' found: try to get IP'
Oct  5 14:47:22 HomeServer root: autoshutdown[903]: INFO: ' _check_networkconfig(): Run: #1: IP-Adress found'
Oct  5 14:47:22 HomeServer root: autoshutdown[903]: INFO: ' 'enp0s25' has IP:         inet 192.168.1.200  netmask 255.255.255.0  broadcast 192.168.1.255'
Oct  5 14:47:22 HomeServer root: autoshutdown[903]: WARN: ' Invalid parameter format: Class: nnn.nnn.nnn]'
Oct  5 14:47:22 HomeServer root: autoshutdown[903]: WARN: ' It is set to 'inet 192.168.1.200 netmask 255.255.255.0 broadcast 192.168.1', which is not a correct synt$
Oct  5 14:47:22 HomeServer root: autoshutdown[903]: WARN: ' Please report this Bug and the CLI-output of 'ifconfig''
Oct  5 14:47:22 HomeServer root: autoshutdown[903]: WARN: ' unsetting NIC[1]: enp0s25 ...'
Oct  5 14:47:22 HomeServer root: autoshutdown[903]: WARN: ' Invalid parameter format: SERVERIP [iii]'
Oct  5 14:47:22 HomeServer root: autoshutdown[903]: WARN: ' It is set to '255', which is not a correct syntax. Maybe parsing 'ifconfig' did something wrong'
Oct  5 14:47:22 HomeServer root: autoshutdown[903]: WARN: ' Please report this Bug and the CLI-output of 'ifconfig''
Oct  5 14:47:22 HomeServer root: autoshutdown[903]: WARN: ' unsetting NIC[1]:  ...'
Oct  5 14:47:22 HomeServer root: autoshutdown[903]: INFO: ' /tmp/autoshutdown created'

It doesn't matter if IP is set to static or DHCP. The error is always the same. In this case the broadcast must be 192.168.1.1

Hopefully this issue can be fixed.
Thank you

**Comment by ryecoaaron** [comment]
The broadcast should be 192.168.1.255.  The script is saying 192.168.1 is incorrect.  The script is getting the broadcast incorrectly.
