### ISSUE TITLE
Translated on Transifex, not synced to Github

### ISSUE THREAD

**Issue by p-bo** [OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown#38]
Thanks for solving this in backup :)
And what about other repos?

They are out of sync too... quick inspection revealed incomplete translation on Github (on Transifex is all translated). And other translation may be older versions than on Transifex. Please synchronize in _all_ repos for translations in all languages...
Many thanks :)

P.S.: if synchronization with Transifex is manual work, so keeping in sync is impossible, what about (for open source projects costless too) Weblate, which can be synchronized automatically:

https://docs.weblate.org/en/latest/api.html#hooks
https://docs.weblate.org/en/latest/admin/continuous.html#github-setup

Incomplete translations:

https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-kerberos/blob/master/usr/share/openmediavault/locale/cs_CZ/openmediavault-kerberos.po

https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-webdav/blob/master/usr/share/openmediavault/locale/cs_CZ/openmediavault-webdav.po

https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-transmissionbt/blob/master/usr/share/openmediavault/locale/cs_CZ/openmediavault-transmissionbt.po

https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-wol/blob/master/usr/share/openmediavault/locale/cs_CZ/openmediavault-wol.po

https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-wakealarm/blob/master/usr/share/openmediavault/locale/cs_CZ/openmediavault-wakealarm.po

https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-openvpn/blob/master/usr/share/openmediavault/locale/cs_CZ/openmediavault-openvpn.po

https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-zfs/blob/master/usr/share/openmediavault/locale/cs_CZ/openmediavault-zfs.po

https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-downloader/blob/master/usr/share/openmediavault/locale/cs_CZ/openmediavault-downloader.po

https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-syncthing/blob/master/usr/share/openmediavault/locale/cs_CZ/openmediavault-syncthing.po

https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-snapraid/blob/master/usr/share/openmediavault/locale/cs_CZ/openmediavault-snapraid.po

https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-jdownloader/blob/master/usr/share/openmediavault/locale/openmediavault-jdownloader.pot

https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-calibre/blob/master/usr/share/openmediavault/locale/cs_CZ/openmediavault-calibre.po

https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-cups/blob/master/usr/share/openmediavault/locale/cs_CZ/openmediavault-cups.po

https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-anacron/blob/master/usr/share/openmediavault/locale/cs_CZ/openmediavault-anacron.po

https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-developer/blob/master/usr/share/openmediavault/locale/cs_CZ/openmediavault-developer.po

https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/blob/master/usr/share/openmediavault/locale/cs_CZ/openmediavault-omvextrasorg.po

https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-mysql/blob/master/usr/share/openmediavault/locale/cs_CZ/openmediavault-mysql.po

https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-nginx/blob/master/usr/share/openmediavault/locale/cs_CZ/openmediavault-nginx.po

https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-unionfilesystems/blob/master/usr/share/openmediavault/locale/cs_CZ/openmediavault-unionfilesystems.po

https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-virtualbox/blob/master/usr/share/openmediavault/locale/cs_CZ/openmediavault-virtualbox.po

https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-rsnapshot/blob/master/usr/share/openmediavault/locale/cs_CZ/openmediavault-rsnapshot.po

https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown/blob/master/usr/share/openmediavault/locale/cs_CZ/openmediavault-autoshutdown.po

https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-docker-gui/blob/master/usr/share/openmediavault/locale/cs_CZ/openmediavault-docker-gui.po

**Comment by ryecoaaron** [comment]
Yes, I am bad about updating the translations (please don't file an issue for every plugin) but the translations can only point to one release of the plugins.  Most of the plugins have been updated for OMV 4.x.  So, you will probably only see the updates in OMV 4.x.

As for switching away from transifex, that would be too much work and the translators would be lost.

Updates pushed to repo for autoshutdown.
