### ISSUE TITLE
Autoshutdown prevented sleep.d

### ISSUE THREAD

**Issue by hackbird001** [OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown#39]
Hello,

i has in etc/pm/sleep.d an script which stops tvheadend and unload the drivers from TVCard.
When i suspend my system on terminal and restart, all works perfectly.

When autoshutdown goes in suspend the script wont work. Is this an bug?

**Comment by nrandon** [comment]
We are not longer using sleep.d and have moved to systemd so i think this can be closed as on 5.1.8 release
