### ISSUE TITLE
HDDIO is wrongly calculated

### ISSUE THREAD

**Issue by Martin-vH** [OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown#45]
From #24 I investigated in how iostat is used by this plug-in. Every first invocation of iostat shows the read/write of the disk since the last boot. For me having a RAID5 this is 5 MB/s for all RAID members. The `-y` option disables this behaviour and shows the IO rates since the last invocation. But this is only working if interval and count parameters are provided. This results in an overall rate of  almost 0 MB/s which is the right value. Therefore the used command in the script needs to be `iostat -ykd 1 1`.

**Comment by nrandon** [comment]
now corrected
