### ISSUE TITLE
Autoshutdown.sh is using systemctl hybrid instead of pm-suspend-hybrid

### ISSUE THREAD

**Issue by jonathanmmm** [OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown#46]
Hello,

I am very glad you gave OMV such a important feature.

My problem is, since the last update of openmediavault-shutdown

The GUI is writing at /etc/autoshutdown.conf not the right Command.

Also for just suspend it writes sytemctl suspend and both are unknown operations.

Can you fix this? Or help me, where the Commands for the selection of GUI are found?

I have already replaced the autoshutdown.sh with the newest here (just copy paste) and reinstalled the package with apt-get install --reinstall openmediavault-autoshutdown
The reinstall gave some errors, but I hope they are okay:

root@MMNAS:~# sudo apt-get install --reinstall openmediavault-autoshutdown
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
0 aktualisiert, 0 neu installiert, 1 erneut installiert, 0 zu entfernen und 0 nicht aktualisiert.
Es müssen 47,1 kB an Archiven heruntergeladen werden.
Nach dieser Operation werden 0 B Plattenplatz zusätzlich benutzt.
Holen:1 https://dl.bintray.com/openmediavault-plugin-developers/arrakis stretch/main amd64 openmediavault-autoshutdown all 4.0.3 [47,1 kB]
Es wurden 47,1 kB in 0 s geholt (110 kB/s).
(Lese Datenbank ... 98372 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../openmediavault-autoshutdown_4.0.3_all.deb ...
Entpacken von openmediavault-autoshutdown (4.0.3) über (4.0.3) ...
openmediavault-autoshutdown (4.0.3) wird eingerichtet ...
Trigger für openmediavault (4.0.19-1) werden verarbeitet ...
Updating locale files ...
Updating file permissions ...
Purging internal cache ...
Restarting engine daemon ...
Trigger für rsyslog (8.24.0-1) werden verarbeitet ...
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fa07e092730>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fa07e092730>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable

I am using OMV 4 with OMV Extras (hope the latest, dont know how to update them), through the GUI all things are up to date and also through ssh with apt-get are all things are up to date.

**Comment by ryecoaaron** [comment]
This behavior was just changed in 4.0.3 (https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown/commit/5aaabd171d6cf3faed2957a1a689083d534e3082) because testing from others had good results.  Maybe they weren't using hybrid?  Looks like hybrid should be systemctl hybrid-sleep though.  I just don't have a good way to test.

**Comment by jonathanmmm** [comment]
I have no set SHUTDOWNCOMMAND="pm-suspend-hybrid" manually and it works.

But when I make a change in the gui it will probably switch back.

**Comment by ryecoaaron** [comment]
Did you try what I suggested?

**Comment by ErdnussFlipS** [comment]
@ryecoaaron: "systemctl hybrid-sleep" works on my machine. "pm-is-supported --suspend-hybrid" returns "0" as exit code, so hybrid sleep is supported.

**Comment by jonathanmmm** [comment]
I can try to add it to the expert settings, but systemctl hybrid was unknown (as far as I know), only with pm it worked not with systemctl.

OMV 4.1.0-1
OMV Extras 4.1.2
Kernel 4.14.0-0.bpo.3-adm64 (I believe it was Kernel 4.14.0-**1**.bpo.3-adm64

**Comment by nrandon** [comment]
obsolete
