### ISSUE TITLE
[Feature request] Use port list for outbound connections, as well.

### ISSUE THREAD

**Issue by davekr8** [OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown#50]
Hey there,
not an issue but some kind of feature request. 

Is there any reason why it's a bad idea to widen the constraints to prevent the system from shutdown also for outbound connections. There are several cases, where this should be considered, e.g., making use of rclone to sync to a cloud storage using target port 433, using rsync to a other target workstation or just to prevent any update process, which grabs data from the web.

I think it's also useful not to interrupt such connection via automatic shutdown.

What do you think ?

**Comment by nrandon** [comment]
closing will not do
