### ISSUE TITLE
autoshutdown is not working in Debian 9

### ISSUE THREAD

**Issue by gersel** [OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown#55]
* autoshutdown.sh contains error: line 1179 (NIC list) : eth0 will be not used anymore in Debian 9,
  new naming scheme!  possible detect existent NICs with "ifquery --list"

* ifconfig command is outdated, use "ip addr show" furthermore

**Comment by ryecoaaron** [comment]
As you probably found, the plugin install net-tools which allows it to keep using these commands.

**Comment by gersel** [comment]
Thank you for the answer. I am using this workaround already, but using "ip addr show" or alike seems the better way for future.
This was my second step after not existing eth0 located...

**Comment by ryecoaaron** [comment]
Are you using the script without the plugin?  There should be no workaround with the plugin because it has a dependency on net-tools being installed.

I try not to touch this script too much because there are too many thing I would want to change and I don't have a way to test them.

**Comment by gersel** [comment]
No. Not normaly. But I tried to start it from shell to understand, what goes on.  ;)

**Comment by ryecoaaron** [comment]
Ah.  That makes more sense.

**Comment by gersel** [comment]
now i tried once again: 
1. started the script 'autoshutdown.sh' (original). 
    For the result look here: 
![omv-bildschirmfoto vom 2019-02-21 19-11-44](https://user-images.githubusercontent.com/24387020/53192251-46655980-360e-11e9-9324-5b0f4ddaa78f.png)
the service is displayed as "red".
2.  'autoshutdown.sh' changed: FORCE_NIC="bond0 enp2s0"
     then started the changed script 'autoshutdown.sh'
For result look here:
![omv-bildschirmfoto vom 2019-02-21 19-18-02](https://user-images.githubusercontent.com/24387020/53192372-96442080-360e-11e9-9860-8d1d96c52fd8.png)
Now the service is "green" ;-D

**Comment by ryecoaaron** [comment]
I guess I don't understand why you have to set FORCE_NIC.  What is the output of:

ip link | awk -F': ' '/: en|: eth|: wlan|: bond|: usb/ {print $2}'

**Comment by gersel** [comment]
Here you are!
![omv-bildschirmfoto vom 2019-02-21 19-40-06](https://user-images.githubusercontent.com/24387020/53193154-99d8a700-3610-11e9-812e-7f1c108f7078.png)
hard coded items...

**Comment by ryecoaaron** [comment]
Ok.  How about:

ip link show up | grep enp2s0
ifconfig enp2s0 | egrep -q "inet "

**Comment by gersel** [comment]
No problem:
![omv-bildschirmfoto vom 2019-02-21 19-55-17](https://user-images.githubusercontent.com/24387020/53194013-b4138480-3612-11e9-8246-cb396e84d56c.png)

**Comment by gersel** [comment]
and the next one:
![omv-bildschirmfoto vom 2019-02-21 19-58-09](https://user-images.githubusercontent.com/24387020/53194176-0e144a00-3613-11e9-8a2b-6b9233a994f4.png)

**Comment by gersel** [comment]
compare to this result:
![omv-bildschirmfoto vom 2019-02-21 20-00-50](https://user-images.githubusercontent.com/24387020/53194362-7cf1a300-3613-11e9-8732-0d684e73ff19.png)

**Comment by ryecoaaron** [comment]
I forgot to remove the quiet flag.  All of your output tells me it should be working.  Not sure what is wrong that changing the code solves.

**Comment by gersel** [comment]
NO. Not all! Look at the first screenshot! The net-tools are existing and i tried to start the original script.
No NIC was found and the service is red!

This result is the consequence of hard coding the NIC-names in line 1179.
Hard coding is never a good idea! 
i am not the great shellscript freak. 
But i learned it hard in the past:
Never do so. never. never. never.  ;-D 

Then i changed the NIC-list in the script! 

I added the name of the NIC in my computer.
Look at the second screenshot and following.
All the other screenshots illustrates the success!
Now the service is green.

sincerelly yours
Gerald Seliger

p.s.:  sorry! My english is bad. It's seldom in use...

**Comment by ryecoaaron** [comment]
I meant the output from the commands I asked you about.

What version of the script are you looking at?  I don't see any hard-coded NIC names especially on line 1179.
