### ISSUE TITLE
[Feature Request] Have autoshutdown log in cron file

### ISSUE THREAD

**Issue by Ansem93** [OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown#58]
Hi, I wanted to suggest a new option:
since autoshutdown use cron, it write in the syslog file every minute. This way it's really hard to read the syslog file.
I solved the problem editing the rsyslog file like that:
- removed the # from cron.* raw
- added "cron," to *.*,auth,authpriv.none

Is it possible to make an option that will edit the rsyslog file and restart syslog?
I would solve it launching a new script: if true then edit the rsyslogfile, if false revert the change;

**Comment by ryecoaaron** [comment]
I don't understand this request.  autoshutdown doesn't use cron and logs to /var/log/autoshutdown.log.  See https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown/blob/master/etc/rsyslog.d/autoshutdown.conf

**Comment by Ansem93** [comment]
Sorry, I forgot to mention the exact log:
Jun 16 00:06:01 Delibird CRON[4270]: (root) CMD (   test -x /usr/sbin/wakealarm && /usr/sbin/wakealarm > /dev/null 2>&1)
Jun 16 00:07:01 Delibird CRON[4331]: (root) CMD (   test -x /usr/sbin/wakealarm && /usr/sbin/wakealarm > /dev/null 2>&1)

Autoshutdown log correctly in his file and it's a blessing :)

Since you autoshutdown, you'll have this log every minute in syslog.
I removed it editing rsyslog.conf since syslog become unreadble.

**Comment by ryecoaaron** [comment]
This is caused by the wakealarm plugin not autoshutdown.
