### ISSUE TITLE
ipv4-mapped into ipv6 addresses are not considered in _check_net_status

### ISSUE THREAD

**Issue by FernetMenta** [OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown#67]
[::ffff:192.168.178.77]:80 vs 192.168.178.25:80

OVM 5 starts nginx like this:
listen [::]:80 default_server ipv6only=off;

As a result autoshutdown won't detect if anybody is logged in to the webgui

**Comment by nrandon** [comment]
close off
