### ISSUE TITLE
ubuntu 14.04

### ISSUE THREAD

**Issue by biosphere2** [OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown#7]
Hi,

I run an ubuntu 14.04 machine (used as a media center and server) and I would like to use this scipt to shut down my machine when it is not in use.
I tried to install it from the .deb file but it was not working good.
I have used omv before and I know in that system it worked perfectly.
Could you help me how to install and configure it in ubuntu?
Thank you.

**Comment by ryecoaaron** [comment]
This is a plugin for OpenMediaVault and only works on OpenMediaVault.
