### ISSUE TITLE
lastest version(5.1.1) has a bug.

### ISSUE THREAD

**Issue by jerry-ch-issue** [OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown#78]
Sorry for can't reappear the bug here, because I already install 5.1.0, and it woks well.

I can describ it a little. when I  save my Configuration, ever enable it, it jump a Dialog box said "Missing 'required' attribute 'checksockets". 

that's all.

**Comment by ryecoaaron** [comment]
Trying clearing your browser cache.

**Comment by nrandon** [comment]
its a browser cache issue I can reproduce it cleaning the cache should fix it

**Comment by jerry-ch-issue** [comment]
got it. thanks

**Comment by jerry-ch-issue** [comment]
It works, thanks, both of you.
