### ISSUE TITLE
lastest version(5.1.1) ERR: '_check_networkconfig(): _check_networkconfig(): No valid network interface found, exiting ...'

### ISSUE THREAD

**Issue by Cyrixxx9** [OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown#79]
Hi
please help with this:

Dec 17 23:11:02 nas autoshutdown[18036]: Dec 17 23:11:02 root: autoshutdown[18036]: INFO: '_check_networkconfig(): ------------------------------------------------------'
Dec 17 23:11:02 nas root: autoshutdown[18036]: INFO: '_check_networkconfig(): ------------------------------------------------------'
Dec 17 23:11:02 nas autoshutdown[18036]: Dec 17 23:11:02 root: autoshutdown[18036]: INFO: '_check_networkconfig(): Finding up network interfaces and associated IPv4 address'
Dec 17 23:11:02 nas root: autoshutdown[18036]: INFO: '_check_networkconfig(): Finding up network interfaces and associated IPv4 address'
Dec 17 23:11:02 nas autoshutdown[18036]: Dec 17 23:11:02 root: autoshutdown[18036]: DEBUG: '_check_networkconfig(): Network interfaces: eth0'
Dec 17 23:11:02 nas root: autoshutdown[18036]: DEBUG: '_check_networkconfig(): Network interfaces: eth0'
Dec 17 23:11:02 nas autoshutdown[18036]: Dec 17 23:11:02 root: autoshutdown[18036]: DEBUG: '_check_networkconfig(): Network interfaces status: unknown'
Dec 17 23:11:02 nas root: autoshutdown[18036]: DEBUG: '_check_networkconfig(): Network interfaces status: unknown'
Dec 17 23:11:02 nas autoshutdown[18036]: Dec 17 23:11:02 root: autoshutdown[18036]: DEBUG: '_check_networkconfig(): Network interfaces IPv4 address: 192.168.1.20'
Dec 17 23:11:02 nas root: autoshutdown[18036]: DEBUG: '_check_networkconfig(): Network interfaces IPv4 address: 192.168.1.20'
Dec 17 23:11:02 nas autoshutdown[18036]: Dec 17 23:11:02 root: autoshutdown[18036]: DEBUG: '_check_networkconfig(): Network interfaces IPv4 address valid: 0'
Dec 17 23:11:02 nas root: autoshutdown[18036]: DEBUG: '_check_networkconfig(): Network interfaces IPv4 address valid: 0'
Dec 17 23:11:02 nas autoshutdown[18036]: Dec 17 23:11:02 root: autoshutdown[18036]: ERR: '_check_networkconfig(): _check_networkconfig(): No valid network interface found, exiting ...'
Dec 17 23:11:02 nas root: autoshutdown[18036]: ERR: '_check_networkconfig(): _check_networkconfig(): No valid network interface found, exiting ...'

**Comment by nrandon** [comment]
Hi, the script is falling as eth0 is in status "unknown" (interface is up with no carrier), rather that status "up" (the interface is up and has a carrier).

Can you post the output the following once the system is visible on the network:
```
$ ip link list eth0
```

The issue is should an interface with state "unknown" be considered as it may eventually come online (i.e. the interface my be configured and be active (up) in the os but internally a cable is disconnected at start-up). As at any time the interface may go to "up" and if not considered buy the script will be overlooked unless there is a script restart.

**Comment by nrandon** [comment]
Can you also post output of:
```
ip link show up eth0
```

**Comment by Cyrixxx9** [comment]
ip link list eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether c6:36:b7:dd:90:13 brd ff:ff:ff:ff:ff:ff

ip link show up eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether c6:36:b7:dd:90:13 brd ff:ff:ff:ff:ff:ff

**Comment by nrandon** [comment]
@Cyrixxx9 thank this is what i was expecting to be honest the interface is up.

Can you try the following script change for me, it should I hope get the script to work for you, and if so I construct a code fix

Current code:
```
1266             [ "$(< "/sys/class/net/${net_iface}/operstate")" == "up" ] && {
```

Change to test:
```
1266             [ "$(< "/sys/class/net/${net_iface}/operstate")" != "down" ] && {
```

let me know if it work for you

**Comment by nrandon** [comment]
woops missed the file to change: /usr/sbin/autoshutdown you need to be root

**Comment by Cyrixxx9** [comment]
It works now, thx:

Dec 18 15:12:50 nas autoshutdown[3154]: Dec 18 15:12:50 root: autoshutdown[3154]: INFO: '_check_networkconfig(): ------------------------------------------------------'
Dec 18 15:12:50 nas root: autoshutdown[3154]: INFO: '_check_networkconfig(): ------------------------------------------------------'
Dec 18 15:12:50 nas autoshutdown[3154]: Dec 18 15:12:50 root: autoshutdown[3154]: INFO: '_check_networkconfig(): Finding up network interfaces and associated IPv4 address'
Dec 18 15:12:50 nas root: autoshutdown[3154]: INFO: '_check_networkconfig(): Finding up network interfaces and associated IPv4 address'
Dec 18 15:12:50 nas autoshutdown[3154]: Dec 18 15:12:50 root: autoshutdown[3154]: DEBUG: '_check_networkconfig(): Network interfaces: eth0'
Dec 18 15:12:50 nas root: autoshutdown[3154]: DEBUG: '_check_networkconfig(): Network interfaces: eth0'
Dec 18 15:12:50 nas autoshutdown[3154]: Dec 18 15:12:50 root: autoshutdown[3154]: DEBUG: '_check_networkconfig(): Network interfaces status: unknown'
Dec 18 15:12:50 nas root: autoshutdown[3154]: DEBUG: '_check_networkconfig(): Network interfaces status: unknown'
Dec 18 15:12:50 nas autoshutdown[3154]: Dec 18 15:12:50 root: autoshutdown[3154]: DEBUG: '_check_networkconfig(): Network interfaces IPv4 address: 192.168.1.20'
Dec 18 15:12:50 nas root: autoshutdown[3154]: DEBUG: '_check_networkconfig(): Network interfaces IPv4 address: 192.168.1.20'
Dec 18 15:12:50 nas autoshutdown[3154]: Dec 18 15:12:50 root: autoshutdown[3154]: DEBUG: '_check_networkconfig(): Network interfaces IPv4 address valid: 0'
Dec 18 15:12:50 nas root: autoshutdown[3154]: DEBUG: '_check_networkconfig(): Network interfaces IPv4 address valid: 0'
Dec 18 15:12:50 nas autoshutdown[3154]: Dec 18 15:12:50 root: autoshutdown[3154]: INFO: '_check_networkconfig(): 'eth0' has IPv4 address: 192.168.1.20'
Dec 18 15:12:50 nas root: autoshutdown[3154]: INFO: '_check_networkconfig(): 'eth0' has IPv4 address: 192.168.1.20'

**Comment by nrandon** [comment]
@Cyrixxx9 Grate I put a fix together to allow for this case, ASAP

**Comment by Cyrixxx9** [comment]
Fixed
