### ISSUE TITLE
add different "force uptime" on weekdays and on weekends

### ISSUE THREAD

**Issue by walterheisenberg** [OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown#8]

**Comment by magicsunday** [comment]
How is the progress here? I would really like to see this feature too.

**Comment by ryecoaaron** [comment]
I haven't seen or heard of any activity on this in months.

**Comment by iliandj** [comment]
Really this option would be very useful. Is there any way to prevent auto shutdown on weekends.

**Comment by der-berni** [comment]
I solved it this way:
first cronjob for fridays 23 o'clock => touch /tmp/itsweekend
another cronjob Mondays 3 o'clock => rm /tmp/itsweekend

in the plugin „expert settings“ at the bottom insert the parameter => PLUGINCHECK="true"

create a new file in /etc/autoshutdown.d
=>
echo „folder=\"/tmp\" \n file=\"itsweekend\" “ > /etc/autoshutdown.d/itsweekend

have fun

**Comment by nrandon** [comment]
added in 5.1.4
