### ISSUE TITLE
typos in logs

### ISSUE THREAD

**Issue by thatso** [OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown#86]
I've spotted some typos in the logs. You might want to correct line 1335 in `/usr/sbin/autoshutdown`:

`_log "INFO: Waiting 5 minuets until the first check"`

to

`_log "INFO: Waiting 5 minutes until the first check"`

and line 1136:

` _log "INFO: Finding available network interfaces and there IPv4 addresses"`

to

` _log "INFO: Finding available network interfaces and their IPv4 addresses"`

Maybe also change line 1354:

`_log "INFO: All active check passed, ${FCNT} cycles until shutdown..."`

to

`_log "INFO: All active checks passed, ${FCNT} cycles until shutdown..."`

**Comment by thatso** [comment]
Friendly reminder: only the first typo was corrected.

**Comment by nrandon** [comment]
My apology i did see the other changes required I have re-open and will fix in the next update

**Comment by nrandon** [comment]
fixed in 5.1.9

**Comment by thatso** [comment]
Much appreciated. Please concentrate on #87 first, some typos can very well wait.  :-)

**Comment by ryecoaaron** [comment]
@thatso I know the typos could wait but I figured if I was pushing out a new package that we might as well get the typo fix in too.    The 87 issue was caused by the my automation that builds the package.
