### ISSUE TITLE
Plugin is inactive after waking up from sleep

### ISSUE THREAD

**Issue by gadric** [OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown#87]
I am refering to the issue described here: https://forum.openmediavault.org/index.php?thread/37902-autoshutdown-plugin-version-5-1-7-is-inactive-when-it-wakes-up-from-sleep/&postID=265497#post265497

Solution: it seems that the file `autoshutdown-restart` in `/lib/systemd/system-sleep/` **not the one in /usr/lib/systemd/system-sleep** needs to have +x. 

with `chmod +x /lib/systemd/system-sleep/autoshutdown-restart` the problem seems to be fixed.

**Comment by nrandon** [comment]
there still an issue here as we not getting the script written as executable after the build not sure where the error is at present as when i build the package manually the script is executable when it is installed

**Comment by ryecoaaron** [comment]
That is the developer plugin's fault.  Fixing it now.  Do you want to fix the typo in the other thread and increment the version to 5.1.8.1 or something?

**Comment by nrandon** [comment]
i can fix the typos in a min

**Comment by nrandon** [comment]
Typo fixes in the repo now @ryecoaaron

**Comment by ryecoaaron** [comment]
5.1.9 in repo now.

**Comment by nrandon** [comment]
@ryecoaaron  check working correctly now will closes off
