### ISSUE TITLE
typo: pm-supend

### ISSUE THREAD

**Issue by davekr8** [OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown#9]
/usr/local/bin/autoshutdown.sh

line 1108:			if [ "$SHUTDOWNCOMMAND" = "pm-supend" -a ! "$PM_SUSPEND" = "true" ]; then

maybe a typo there ?!

**Comment by walterheisenberg** [comment]
what do you mean exactly? I can't see one

**Comment by davekr8** [comment]
supend ->  suspend

there is no command supend, this throws an exception.

**Comment by walterheisenberg** [comment]
Ooooops!
I missed this, thx
Will fix it asap

**Comment by davekr8** [comment]
i appreciate it !

spend several minutes to find this typo, too ... strange, what perception sometime do to you.
