### ISSUE TITLE
autoshutdown not working with debian kernel 5.10.0-0.bpo.4-amd64

### ISSUE THREAD

**Issue by FRYYYYYY** [OpenMediaVault-Plugin-Developers/openmediavault-autoshutdown#97]
Hallo, I am facing out a strange problem. 

Since update to Debian kernel 5.10.0-0.bpo.**4**-amd64 autoshutdown starts to recognize external IP addresses and writes down that my client is active and connected on all ports to scan (that’s wrong; in my example only port 22 and 80 is correct):

`Apr  5 01:59:46 SERVER autoshutdown[22412]: root: INFO: 'main(): ------------------------------------------------------'
Apr  5 01:59:46 SERVER autoshutdown[22412]: root: INFO: 'main(): New supervision cycle started, checking system activity'
Apr  5 01:59:46 SERVER autoshutdown[22412]: root: INFO: '_check_net_status(): Found 4 active connection on port 21 (FTP) from: 88.99.115.46, 99.81.153.144, 172.104.245.130, 192.168.178.240'
Apr  5 01:59:46 SERVER autoshutdown[22412]: root: INFO: '_check_net_status(): Found 4 active connection on port 22 (SSH) from: 88.99.115.46, 99.81.153.144, 172.104.245.130, 192.168.178.240'
Apr  5 01:59:46 SERVER autoshutdown[22412]: root: INFO: '_check_net_status(): Found 4 active connection on port 80 (HTTP) from: 88.99.115.46, 99.81.153.144, 172.104.245.130, 192.168.178.240'Apr  5 01:59:46 SERVER autoshutdown[22412]: root: INFO: '_check_net_status(): Found 4 active connection on port 3689 (DAAP) from: 88.99.115.46, 99.81.153.144, 172.104.245.130, 192.168.178.240'
Apr  5 01:59:46 SERVER autoshutdown[22412]: root: INFO: '_check_net_status(): Found 4 active connection on port 6991 (BITTORRENT) from: 88.99.115.46, 99.81.153.144, 172.104.245.130, 192.168.178.240'
Apr  5 01:59:46 SERVER autoshutdown[22412]: root: INFO: '_check_net_status(): Found 4 active connection on port 9091 (BITTORRENT_WEBIF) from: 88.99.115.46, 99.81.153.144, 172.104.245.130, 192.168.178.240'
Apr  5 01:59:46 SERVER autoshutdown[22412]: root: INFO: '_check_net_status(): Found 4 active connection on port 32400 (PLEXMEDIASERVER) from: 88.99.115.46, 99.81.153.144, 172.104.245.130, 192.168.178.240'
Apr  5 01:59:46 SERVER autoshutdown[22412]: root: INFO: '_check_net_status(): Found 4 active connection on port 49152 (UPNP) from: 88.99.115.46, 99.81.153.144, 172.104.245.130, 192.168.178.240'
Apr  5 01:59:46 SERVER autoshutdown[22412]: root: INFO: '_check_net_status(): Found 32 active socket(s) from port(s): 21,22,80,3689,6991,9091,32400,49152'
Apr  5 01:59:46 SERVER autoshutdown[22412]: root: INFO: 'main(): Sleep for 180s'
` 

I am not connected to all of these ports. And I don’t know why „88.99.115.46, 99.81.153.144, 172.104.245.130“ are listed.

Back with kernel 5.10.0-0.bpo.3-amd64 everything works fine.

**Comment by nrandon** [comment]
hi this does look a little odd. however I do not have 5.10.0-0.bpo.4-amd64 available to download so I cannot confirm that this is the issue. Did you get 5.10.0-0.bpo.4-amd64 from Debian backports ?

Also so I can help you, I need the script placed with the debug output (this can be set in the GUI by turning on Verbose output) and posting the output here. However, I should state there is no magic to how this test work it simply uses the 'ss -n' command to get the connection and then send it to an awk filter to get the relevant established connection relating to your server IP.

**Comment by FRYYYYYY** [comment]
From the very normal official source but installed directly via apt-get.

Funnily enough, it works now - even if I jump back to the ....4... kernel again. I close the issue. 

Thanks for the quick reply though!

**Comment by nrandon** [comment]
I installed 5.10.0-0.bpo.4-amd64 and double checked this work on my system and I am not seeing the issue you described. However it looks as if you resoled it anyway (glade you manage to fix it). If you still have a problem re-open the ticket and place the debug log in it and I look at it ASAP.
